# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.8.post28+gf80b25a.d20230604'
__version_tuple__ = version_tuple = (0, 0, 8, 'gf80b25a.d20230604')
