name: Build with Conda

on: [push]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          environment-file: environment.yml
          init-shell: >-
            bash
            cmd.exe
          cache-environment: true
          post-cleanup: 'all'
      - name: Import numpy in micromamba environment (bash)
        run: python -c "import numpy"
        shell: bash -el {0}
        
